// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/SALutHere/avito-2025-autumn-backend-internship/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PRRepository is an autogenerated mock type for the PRRepository type
type PRRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, pr
func (_m *PRRepository) Create(ctx context.Context, pr *domain.PullRequest) error {
	ret := _m.Called(ctx, pr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PullRequest) error); ok {
		r0 = rf(ctx, pr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, id
func (_m *PRRepository) Exists(ctx context.Context, id string) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PRRepository) GetByID(ctx context.Context, id string) (*domain.PullRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.PullRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.PullRequest); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByReviewer provides a mock function with given fields: ctx, reviewerID
func (_m *PRRepository) ListByReviewer(ctx context.Context, reviewerID string) ([]domain.PullRequest, error) {
	ret := _m.Called(ctx, reviewerID)

	if len(ret) == 0 {
		panic("no return value specified for ListByReviewer")
	}

	var r0 []domain.PullRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.PullRequest, error)); ok {
		return rf(ctx, reviewerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.PullRequest); ok {
		r0 = rf(ctx, reviewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PullRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, reviewerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateReviewers provides a mock function with given fields: ctx, id, reviewers
func (_m *PRRepository) UpdateReviewers(ctx context.Context, id string, reviewers []string) error {
	ret := _m.Called(ctx, id, reviewers)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReviewers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, id, reviewers)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusAndMergedAt provides a mock function with given fields: ctx, id, status, mergedAt
func (_m *PRRepository) UpdateStatusAndMergedAt(ctx context.Context, id string, status domain.PRStatus, mergedAt *time.Time) error {
	ret := _m.Called(ctx, id, status, mergedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusAndMergedAt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.PRStatus, *time.Time) error); ok {
		r0 = rf(ctx, id, status, mergedAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPRRepository creates a new instance of PRRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPRRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PRRepository {
	mock := &PRRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
