// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/SALutHere/avito-2025-autumn-backend-internship/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// StatsRepository is an autogenerated mock type for the StatsRepository type
type StatsRepository struct {
	mock.Mock
}

// CountAssignmentsByUser provides a mock function with given fields: ctx
func (_m *StatsRepository) CountAssignmentsByUser(ctx context.Context) ([]domain.UserAssignmentStat, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountAssignmentsByUser")
	}

	var r0 []domain.UserAssignmentStat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.UserAssignmentStat, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.UserAssignmentStat); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserAssignmentStat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountReviewersByPR provides a mock function with given fields: ctx
func (_m *StatsRepository) CountReviewersByPR(ctx context.Context) ([]domain.PRReviewerStat, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountReviewersByPR")
	}

	var r0 []domain.PRReviewerStat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.PRReviewerStat, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.PRReviewerStat); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PRReviewerStat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStatsRepository creates a new instance of StatsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatsRepository {
	mock := &StatsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
